### Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you might choose one over the other.


Label & Ordinal Encoding works almost same but have some difference such as 
 - Label can only applies to targeted variable i.e one column at once but Ordinal can be applied to 1 or more columns at once
 - In Ordinal we can specify the order in which our categorical variable labels 
 
Example: if we have multiple features in our dataset which needs encoding then we can go with Ordinal or we wanna categorize there order in which they labelled else we go with Label encoding 

### Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.


<b>Target Guided Ordinal Encoding</b> based on relationship with target variables, used when we have lots of unique categories in feature.
In this we replace our categorical data with the mean or median of the target variable which makes our prediction more accurate

In [14]:
# example 
import seaborn as sns
import pandas as pd

tips_df = sns.load_dataset('tips')
time_mean = tips_df.groupby('time').mean()['total_bill'].round(3).to_dict()
tips_df['time_encoded']= tips_df['time'].map(time_mean)
tips_df = tips_df.drop('time',axis = 1)
tips_df

# time column encoded and replaced with mean  time_encoded which share direct relation with target i.e total_bill

total_bill   tip     sex smoker   day  size time_encoded
0         16.99  1.01  Female     No   Sun     2       20.797
1         10.34  1.66    Male     No   Sun     3       20.797
2         21.01  3.50    Male     No   Sun     3       20.797
3         23.68  3.31    Male     No   Sun     2       20.797
4         24.59  3.61  Female     No   Sun     4       20.797
..          ...   ...     ...    ...   ...   ...          ...
239       29.03  5.92    Male     No   Sat     3       20.797
240       27.18  2.00  Female    Yes   Sat     2       20.797
241       22.67  2.00    Male    Yes   Sat     2       20.797
242       17.82  1.75    Male     No   Sat     2       20.797
243       18.78  3.00  Female     No  Thur     2       20.797

[244 rows x 7 columns]

### Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?


In [ ]:
# Covariance measures how much changes in one varaible due to change in another variable 

# It's quiet important in statistical analysis as it help us to find relevant column to which our data relies 
# and we can also skip those column whos Covariance low or Negative which further fasten our analysis 

# covariance calculated in python using inbuilt function 
cov()  we can use this with both numpy array or Pandas Dataframe
# this gave us the covariance of each numerical column with respect to each and every column 

### Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.


In [15]:
#importing relevant libraries 

import pandas as pd 
from sklearn.preprocessing import LabelEncoder
data = {'Color': ['red','blue','gree'],'Size': ['small','medium','large'],'Material' : ['wood','metal','plastic']}
df = pd.DataFrame(data)

#performing Label encoding
size_encoder = LabelEncoder()
size_encoder.fit_transform(df[['Size']])
#getting encoded values from our model
size_encoder.transform([['small']])

#this will gave us array[2] as first Size sort alphabetically then labelled
#similarly we could encode Color and Materials too just change in fit_transform 

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [18]:
size_encoder.transform([['large']]) 

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0])

### Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.


In [72]:
#creating a dataframe which has age, income and education level and related data 
data = {'age':[12,25,26,73,23,34,63,23,35],'Income':[0,20300,12000,5200,29398,52020,102029,30028,70008], 'Education Level':['High School','Bachlor','High School','Masters','Bachlor','Masters','PhD','Masters','PhD']}
df = pd.DataFrame(data)

# lets Encode Education level soo we can find covariance of all 
# here we use ordinal encoding 
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[['High School','Bachlor','Masters','PhD']])
df['Education Level--']=encoder.fit_transform(df[['Education Level']])

df = df.drop('Education Level',axis=1)
df

age  Income  Education Level--
0   12       0                0.0
1   25   20300                1.0
2   26   12000                0.0
3   73    5200                2.0
4   23   29398                1.0
5   34   52020                2.0
6   63  102029                3.0
7   23   30028                2.0
8   35   70008                3.0

In [73]:
df.corr()
# so as we saw there's strong correlation btw age & income with Education level and some extend of relation with 
# income and age

age    Income  Education Level--
age                1.000000  0.375416           0.625236
Income             0.375416  1.000000           0.798175
Education Level--  0.625236  0.798175           1.000000

In [74]:
df.cov()
# reading covariance a bit difficult due to exagerated values but we can easily spot 
# income and education level has high covariance and same for income and age 

age        Income  Education Level--
age                   403.361111  2.517431e+05          14.194444
Income             251743.097222  1.114798e+09       30124.763889
Education Level--      14.194444  3.012476e+04           1.277778

### Q6. You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for each variable, and why?


In [36]:
data = {'Gender' : ['Male','Female','Female', 'Male'], 'Education Level' : ['High School','Bachelor s','Masters','PhD'],
       'Employment Status' : ['Unemployed','Part-Time', 'Full Time','Unemployed']}
df = pd.DataFrame(data)


# for Gender we can use label encoding as in that Female stands for 0 and male 1 
gen_encoder = LabelEncoder()
gen_encoder.fit_transform(df[['Gender']])

# for Education level we choose Ordinal encoding as we need to define order in specific manner we can't rely on alpha sorting
from sklearn.preprocessing import OrdinalEncoder
edu_encoder = OrdinalEncoder(categories=[['High School','Bachelor s','Masters','PhD']])
edu_encoder.fit_transform(df[['Education Level']])

# for "Employment Status" again we gone choose Ordinal Encoding
emp_encoder = OrdinalEncoder(categories=[['Unemployed','Part-Time', 'Full Time']])
emp_encoder.fit_transform(df[['Employment Status']])

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[0.],
       [1.],
       [2.],
       [0.]])

### Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/ East/West). Calculate the covariance between each pair of variables and interpret the results.

In [82]:
import numpy as np 
import pandas as pd 
n = 5
#creating variable and filling some random values 
temp = np.random.normal(40,10,n)
humidity = np.random.normal(60,10,n) 
weather = np.random.choice(['Sunny','Cloudy','Rainy'],n)
wind = np.random.choice(['North','South','East','West'],n)
#now puting all these in one dataframe
df = pd.DataFrame({'Temperature':temp,
                   'Humidity': humidity,
                   'Weather Condition': weather,
                   'Wind Direction': wind})
df

Temperature   Humidity Weather Condition Wind Direction
0    34.313961  47.062878             Rainy          South
1    37.964830  42.946016             Sunny          North
2    36.950573  57.723541             Rainy           East
3    44.383696  72.613033             Sunny          North
4    45.983333  46.023631             Rainy           East

In [83]:
# Covariance 
df.cov()
#cov btw Humidity and temperature is 21 which indicates that there is +ve relationship btw them 

Temperature    Humidity
Temperature    25.189111   21.040582
Humidity       21.040582  147.902444

In [84]:
df.corr()

# correlation is 0.344 i.e they do have some relationship but not that strong 

Temperature  Humidity
Temperature     1.000000  0.344718
Humidity        0.344718  1.000000